# Generated by Django 3.2.8 on 2021-10-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_administration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
