# Generated by Django 3.2.8 on 2021-10-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
