# Generated by Django 3.2.8 on 2021-10-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211025_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='employee_title',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
    ]
