# Generated by Django 3.2.8 on 2021-10-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_leave_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approve_status',
            field=models.BooleanField(default=False),
        ),
    ]
