# Generated by Django 3.2.14 on 2023-02-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conveyane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conveyance_amount', models.FloatField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('Reason', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
