# Generated by Django 3.2.14 on 2023-02-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workname', models.CharField(max_length=255)),
                ('WorkDiscription', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Partialy Completed', 'Partialy Completed'), ('Taken Over', 'Taken Over'), ('pending', 'pending')], max_length=255)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.CharField(blank=True, max_length=255, null=True)),
                ('CompletionStatus', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
